Repository codezonediitj/pydatastructs, pull requests merged in 2022-03, with the labels that each got.

#490 fixed some typo
  CODE_OF_CONDUCT.md
Labels: documentation

#492 Fixed grammatical errors in README.md
  README.md
Labels: documentation

#482 Adding C++ backend for `pydatastructs.quick_sort`
  pydatastructs/linear_data_structures/_backend/cpp/algorithms/algorithms.cpp
  pydatastructs/linear_data_structures/_backend/cpp/algorithms/quick_sort.hpp
  pydatastructs/linear_data_structures/_backend/cpp/arrays/DynamicOneDimensionalArray.hpp
  pydatastructs/linear_data_structures/_extensions.py
  pydatastructs/linear_data_structures/algorithms.py
  pydatastructs/linear_data_structures/tests/benchmarks/test_algorithms.py
  pydatastructs/linear_data_structures/tests/test_algorithms.py
  pydatastructs/utils/_backend/cpp/utils.hpp
  scripts/build/add_dummy_submodules.py
  scripts/build/delete_dummy_submodules.py
  scripts/build/dummy_submodules_data.py
Labels: linear_data_structures, algorithms, linear_data_structures.algorithms, cpp

#483 Added `ArraySegmentTree` and `RangeQueryDynamic`
  AUTHORS
  pydatastructs/miscellaneous_data_structures/__init__.py
  pydatastructs/miscellaneous_data_structures/algorithms.py
  pydatastructs/miscellaneous_data_structures/segment_tree.py
  pydatastructs/miscellaneous_data_structures/sparse_table.py
  pydatastructs/miscellaneous_data_structures/tests/test_range_query_dynamic.py
  pydatastructs/utils/tests/test_code_quality.py
Labels: trees, Needs More Work
